### GET token from Auth0

curl --request GET \
  --url http://localhost:5035/catalog \
  --header 'authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImU3MVlrdVUzN3J1dEUtLV9WUlRoRCJ9.eyJpc3MiOiJodHRwczovL2Rldi1tcTR1Y25nazg1dmp2NGx0LnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJ3WnhIeHJ2MnltQW9TWjNtM1gzMm9oZ1V3cURPTkh5OEBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9qYWRlLWNvYnJhIiwiaWF0IjoxNzQ1MTA2MjgxLCJleHAiOjE3NDUxOTI2ODEsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyIsImF6cCI6IndaeEh4cnYyeW1Bb1NaM20zWDMyb2hnVXdxRE9OSHk4In0.Q8BLUGqq5Eas0uxlfb-cMEn-SjlifaCol7WkVu5x41FBa1tg3Crjx-AjnQrzMtSGEHIuPZztfnHZ_j8Ph-aFvhsGO9ya7ExpywKNAjpkewiX0iEvBt3fp81GkuHfrbAko0L1eIapuywhWyryYyiMFFq4sRcuDobMcjdebmZuRi1sjfaB4DzTwoFSLijewYeHYLsWuG0a-DjeQ3_dCbM7zzJrtPui-wPe-eucrDcXt1EyTpMJMF-W6y2oZvmANun3LILQvArlnTCzH2tL9idKPwxxB8h3Mjl059t-SfqjbBDnR6RWdH7MDky8IB9TLMJCZeBDtZQvN58RB_4M4oqQ0Q'


### DELETE a Item to the Catalog Collection

curl --request DELETE \
  --url https://localhost:5035/catalog/3 \
  --header 'authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImU3MVlrdVUzN3J1dEUtLV9WUlRoRCJ9.eyJpc3MiOiJodHRwczovL2Rldi1tcTR1Y25nazg1dmp2NGx0LnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJ3WnhIeHJ2MnltQW9TWjNtM1gzMm9oZ1V3cURPTkh5OEBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9qYWRlLWNvYnJhIiwiaWF0IjoxNzQ1MTA2MjgxLCJleHAiOjE3NDUxOTI2ODEsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyIsImF6cCI6IndaeEh4cnYyeW1Bb1NaM20zWDMyb2hnVXdxRE9OSHk4In0.Q8BLUGqq5Eas0uxlfb-cMEn-SjlifaCol7WkVu5x41FBa1tg3Crjx-AjnQrzMtSGEHIuPZztfnHZ_j8Ph-aFvhsGO9ya7ExpywKNAjpkewiX0iEvBt3fp81GkuHfrbAko0L1eIapuywhWyryYyiMFFq4sRcuDobMcjdebmZuRi1sjfaB4DzTwoFSLijewYeHYLsWuG0a-DjeQ3_dCbM7zzJrtPui-wPe-eucrDcXt1EyTpMJMF-W6y2oZvmANun3LILQvArlnTCzH2tL9idKPwxxB8h3Mjl059t-SfqjbBDnR6RWdH7MDky8IB9TLMJCZeBDtZQvN58RB_4M4oqQ0Q'